version: '3'
services:
  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./microservice/app/:/code/app/
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db_postgres
    networks:
      - mynetwork
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-postgres
    ports:
      - "8001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: spreddy8951@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Surya@04
    depends_on:
      - db_postgres
    networks:
      - mynetwork

  db_postgres:  
    image: postgres:14.3-alpine  
    hostname: db_postgres  
    container_name: db_postgres  
    restart: on-failure  
    environment:  
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=1234  
    ports:  
      - "5432:5432"  
    volumes:  
      - db-postgres:/var/lib/postgresql/data  
    networks:  
      - mynetwork
networks:
  mynetwork:
    external: true
volumes:  
  db-postgres:  
    driver: local  
  
   